// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(geolist) {
    var comp, ei, entry, i, j, len, len1, scene, track, tracks;
    comp = {
      meta: {
        mimetype: 'application/x-daoplayer-composition',
        version: 1,
        description: 'Generated by geolist2daoplayer, ' + (new Date())
      },
      tracks: [],
      scenes: [],
      context: {
        waypoints: [],
        routes: []
      }
    };
    for (ei = i = 0, len = geolist.length; i < len; ei = ++i) {
      entry = geolist[ei];
      scene = {
        name: 'scene_' + ei,
        partial: false,
        tracks: [],
        updatePeriod: 1,
        waypoints: {},
        routes: {}
      };
      comp.scenes.push(scene);
      if (entry.track == null) {
        console.error('Warning: entry [' + ei + '] has no track');
        continue;
      }
      if (entry.track.md5 == null) {
        console.error('Warning: entry [' + ei + '] track has no md5');
        continue;
      }
      scene.tracks.push({
        name: entry.track.md5,
        volume: 1
      });
    }
    tracks = {};
    for (j = 0, len1 = geolist.length; j < len1; j++) {
      entry = geolist[j];
      if ((entry.track != null) && (entry.track.md5 != null) && (tracks[entry.track.md5] == null)) {
        track = {
          name: entry.track.md5,
          pauseIfSilent: true,
          files: [
            {
              path: entry.track.md5 + '.' + entry.track.file_ext,
              trackPos: 0,
              filePos: 0,
              length: entry.track.duration_s,
              repeats: 1
            }
          ]
        };
        tracks[track.name] = track;
        comp.tracks.push(track);
      }
    }
    return comp;
  };

}).call(this);
